version: '3.4'

services:
  tiendaservice.api.author:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44350
    ports:
      - "58690:80"
      - "44350:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  tiendaservice.api.book:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "58691:80"


  tiendaservice.webapi.cart:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Book=http://tiendaservice.api.book
      - Services__Author=http://tiendaservice.api.author
    ports:
      - "58692:80"


  tiendaservice.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Author=http://tiendaservice.api.gateway
    depends_on:
      - tiendaservice.api.book
    ports:
      - "58695:80"

