version: '3.4'

services:
  tiendaservice.api.author:
    image: ${DOCKER_REGISTRY-}tiendaserviceapiauthor
    build:
      context: .
      dockerfile: TiendaService.Api.Author/Dockerfile
  tiendaservice.api.book:
    image: ${DOCKER_REGISTRY-}tiendaserviceapibook
    build:
      context: .
      dockerfile: TiendaService.Api.Book/Dockerfile

  tiendaservice.webapi.cart:
    image: ${DOCKER_REGISTRY-}tiendaservicewebapicart
    build:
      context: .
      dockerfile: TiendaService.WebApi.Cart/Dockerfile

  tiendaservice.api.gateway:
    image: ${DOCKER_REGISTRY-}tiendaserviceapigateway
    build:
      context: .
      dockerfile: TiendaService.Api.Gateway/Dockerfile

networks:
  default:
    external:
      name : TiendaMicroservice



